# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Cargar archivos de configuración adicionales
#

DOTFILES_PATH=~/dotfiles
SHELL_FILES=$DOTFILES_PATH/shell

MY_ZSH_DIR=$SHELL_FILES/zsh_shell




source $MY_ZSH_DIR/init.sh


eval "$(starship init zsh)"
eval "$(zoxide init zsh)"
eval "$(mise activate zsh)"


# Configuraciones adicionales de Zsh pueden ir aquí
# ...

# Ejemplo de configuración adicional
#export PATH="$HOME/bin:$PATH"
