# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Cargar archivos de configuración adicionales
#

DOTFILES_PATH=~/dotfiles
SHELL_FILES=$DOTFILES_PATH/shell

ZSH_CUSTOM=$SHELL_FILES/zsh_shell


source $ZSH_CUSTOM/exports.sh
source $OH_MY_ZSH/oh-my-zsh.sh
source $ZSH_CUSTOM/aliases.sh
source $ZSH_CUSTOM/functions.sh
source $ZSH_CUSTOM/init.sh
source $ZSH_CUSTOM/plugins.sh
source $ZSH_CUSTOM/themes.sh


# Configuraciones adicionales de Zsh pueden ir aquí
# ...

# Ejemplo de configuración adicional
#export PATH="$HOME/bin:$PATH"
