# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Cargar archivos de configuración adicionales
#
export XDG_CONFIG_HOME=$HOME/.config
DOTFILES_PATH=~/dotfiles/shell
SHELL_FILES=$DOTFILES_PATH

MY_ZSH_DIR=$SHELL_FILES/zsh_shell




source $MY_ZSH_DIR/init.sh


eval "$(starship init zsh)"
eval "$(zoxide init zsh)"
eval "$(mise activate zsh)"

fastfetch

# Configuraciones adicionales de Zsh pueden ir aquí
# ...

# Ejemplo de configuración adicional
#export PATH="$HOME/bin:$PATH"


