# Cargar archivos de configuración adicionales
#

DOTFILES_PATH=~/dotfiles
SHELL_FILES=$DOTFILES_PATH/shell

source $SHELL_FILES/aliases.sh
source $SHELL_FILES/functions.sh
source $SHELL_FILES/init.sh
source $SHELL_FILES/exports.sh


# Configuraciones adicionales de Zsh pueden ir aquí
# ...

# Ejemplo de configuración adicional
#export PATH="$HOME/bin:$PATH"

